2021-12-05 17:20:31,058 - trainer.py[line:25] - INFO: Running with identifier 20211205_172031
2021-12-05 17:20:31,058 - trainer.py[line:27] - INFO: Saving log to log\rot360\20211205_172031\run.log
2021-12-05 17:20:31,059 - trainer.py[line:28] - INFO: Using args: [('log_name', 'rot360'), ('data_train', 'Shared/Rot360'), ('data_eval', None), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 20), ('log_dir', 'log'), ('tf_dir', 'tensorboard'), ('output_dir', 'output'), ('not_ignore_warning', False), ('enable_tensorboard', True), ('pack', True)]
2021-12-05 17:20:31,060 - trainer.py[line:39] - INFO: Using tensorboard, store at: tensorboard\rot360\20211205_172031
2021-12-05 17:20:31,061 - trainer.py[line:40] - INFO: Using training data: Shared/Rot360
2021-12-05 17:20:31,061 - trainer.py[line:42] - INFO: Pack this file using this command if training finished: --log_dir log --log_name rot360 --identifier 20211205_172031 --output_checkpoint_dir checkpoint --data_dir Shared/Rot360
2021-12-05 17:20:31,061 - train.py[line:127] - INFO: Running model resnet50
2021-12-05 17:20:31,061 - train.py[line:67] - WARNING: Dataset not found, searching renamed-dataset......
2021-12-05 17:20:31,061 - train.py[line:74] - WARNING: Load dataset with renaming dataset......
2021-12-05 17:20:31,062 - train.py[line:79] - WARNING: Unable to load renamed-dataset!
2021-12-05 17:20:31,062 - trainer.py[line:54] - ERROR: Cannot load file containing pickled data when allow_pickle=False
