2021-11-29 00:25:26,734 - main.py[line:24] - INFO: Running with identifier 20211129_002526
2021-11-29 00:25:26,735 - main.py[line:26] - INFO: Saving log to log\cifar10\20211129_002526\run.log
2021-11-29 00:25:26,735 - main.py[line:27] - INFO: Using args: [('log_name', 'cifar10'), ('data_train', 'dataset/cifar_10_train'), ('data_eval', 'dataset/cifar_10_test'), ('output_checkpoint_dir', 'checkpoint'), ('eval_per_epoch', 20), ('log_dir', 'log'), ('not_ignore_warning', False)]
2021-11-29 00:25:26,735 - train.py[line:82] - INFO: Running model resnet50
2021-11-29 00:25:31,069 - main.py[line:43] - INFO: Keyboard Interrupt
